# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-06 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pdfuploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='uploaded_dtm',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 6, 0, 37, 41, 227067, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
