# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-06 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfuploader', '0002_storedfile_uploaded_dtm'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='size_bytes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
